import type { Metadata } from "next";
import { signInWithCredentials } from "@/server/actions/SignUpWithCardentials";
/**
 *
 * @todo - The metadata for the login page
 */
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "steezglue-login",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}

export default async function LoginPage() {
  // if (!session?.user.email) {
  //   redirect("/auth/signup");
  // }

  return (
    <form action={signInWithCredentials}>
      <input name="email" type="email" placeholder="Email" required />
      <input name="password" type="password" placeholder="Password" required />
      <button type="submit">Sign in</button>
    </form>
  );

  //other sign methods too
}
