import type { Metadata } from "next";
import { signIn } from "next-auth/react";

/**
 *
 * @todo - The metadata for the login page
 */
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "steezglue-login",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}

export default function LoginPage() {
  return (
    <form
      action={async () => {
        "use server";
        await signIn("credentials", { email: "abais", password: "sajsja" });
      }}
    >
      t
      <input name="email" type="email" placeholder="Email" required />
      <input name="password" type="password" placeholder="Password" required />
      <button type="submit">Sign in</button>
    </form>
  );

  //other sign methods too
}
