import type { Metadata } from "next";
import { signIn, signout } from "next-auth/react";
import { getServerAuthSession } from "@/server/auth";
import { redirect } from "next/navigation";
/**
 *
 * @todo - The metadata for the login page
 */
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "steezglue-login",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}

export default async function LoginPage() {
  const session = await getServerAuthSession();
  
  if (!session?.user.email) {
    redirect("/auth/signup");
  }
  

  return (
    <form
      action={async () => {
        "use server";
        await signIn("credentials", { email: "abais", password: "sajsja" });
      }}
    >
      t
      <input name="email" type="email" placeholder="Email" required />
      <input name="password" type="password" placeholder="Password" required />
      <button type="submit">Sign in</button>
    </form>
  );

  //other sign methods too
}
