import type { Metadata } from "next";

/**
 *
 * @todo - The metadata for the signup page
 */

export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "steezglue-signup",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}
export default function SignUpPage() {
  return <div>signup page</div>;
}
