import type { Metadata } from "next";

/**
 *
 * @todo - The metadata for the ForgetPasswordPage page
 * todo implement forgePassword
 */
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "steezglue-login",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}

export default function ForgetPasswordPage() {
  return <div>forget password page</div>;
}
