import type { Metadata } from "next";

/**
 *
 * @todo - The metadata for the dashboard page
 */
export async function generateMetadata(): Promise<Metadata> {
  return {
    title: "steezglue-dashboard",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/favicon.ico" }],
  };
}
export default function DashBoardPage() {
  return <div>dashboard page</div>;
}
